version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test1234

  document:
    build: ./document
    volumes:
      - ./document:/app
    depends_on:
      - neo4j

  review:
    build: ./review
    volumes:
      - ./review:/app
    depends_on:
      - neo4j

  labels:
    build: ./labels
    volumes:
      - ./labels:/app
    depends_on:
      - neo4j
    
  settings:
    build: ./settings
    volumes:
      - ./settings:/app
    depends_on:
      - neo4j

  upload:
    build: ./upload
    volumes:
      - ./upload:/app
    depends_on:
      - neo4j

  ui:
    build: ./ui
    volumes:
      - ./ui:/app
    depends_on:
      - neo4j
      - upload
      - document
      - review
      - settings
    environment:
      - DOCUMENT_PORT=${DOCUMENT_PORT}
      - REVIEW_PORT=${REVIEW_PORT}
      - UI_PORT=${UI_PORT}
      - LABELS_PORT=${LABELS_PORT}
      - SETTINGS_PORT=${SETTINGS_PORT}
      - UPLOAD_PORT=${UPLOAD_PORT}

  nginx:
    image: nginx:latest
    ports:
      - "${DOCUMENT_PORT}:${DOCUMENT_PORT}"
      - "${REVIEW_PORT}:${REVIEW_PORT}"
      - "${UI_PORT}:${UI_PORT}"
      - "${LABELS_PORT}:${LABELS_PORT}"
      - "${SETTINGS_PORT}:${SETTINGS_PORT}"
      - "${UPLOAD_PORT}:${UPLOAD_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    depends_on:
      - ui
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      - DOCUMENT_PORT=${DOCUMENT_PORT}
      - REVIEW_PORT=${REVIEW_PORT}
      - UI_PORT=${UI_PORT}
      - LABELS_PORT=${LABELS_PORT}
      - SETTINGS_PORT=${SETTINGS_PORT}
      - UPLOAD_PORT=${UPLOAD_PORT}