version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test1234

  # Individual services
  document:
    build: ./document
    volumes:
      - ./document:/app
    depends_on:
      - neo4j
  upload:
    build: ./upload
    volumes:
      - ./upload:/app
    depends_on:
      - neo4j

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - document
      - review
      - upload
