version: '3'
services:
  jena:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./jena/data:/fuseki/data
    environment:
      - ADMIN_PASSWORD=test1234
      - JVM_ARGS=-Xmx2g
      - TDB=2

  document:
    build: ./document
    volumes:
      - ./document:/app
    depends_on:
      - jena

  review:
    build: ./review
    volumes:
      - ./review:/app
    depends_on:
      - jena

  upload:
    build: ./upload
    volumes:
      - ./upload:/app
    depends_on:
      - jena

  ui:
    build: ./ui
    volumes:
      - ./ui:/app
    depends_on:
      - document
      - jena
      - review
      - upload
    environment:
      - DOCUMENT_PORT=${DOCUMENT_PORT}
      - REVIEW_PORT=${REVIEW_PORT}
      - UI_PORT=${UI_PORT}
      - UPLOAD_PORT=${UPLOAD_PORT}

  nginx:
    image: nginx:latest
    ports:
      - "${DOCUMENT_PORT}:${DOCUMENT_PORT}"
      - "${REVIEW_PORT}:${REVIEW_PORT}"
      - "${UI_PORT}:${UI_PORT}"
      - "${UPLOAD_PORT}:${UPLOAD_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    depends_on:
      - ui
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      - DOCUMENT_PORT=${DOCUMENT_PORT}
      - REVIEW_PORT=${REVIEW_PORT}
      - UI_PORT=${UI_PORT}
      - UPLOAD_PORT=${UPLOAD_PORT}
