version: '3'
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test1234

  document:
    build: ../../../document
    volumes:
      - ../../../document:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  export:
    build: ../../../export
    volumes:
      - ../../../export:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  import-events:
    build: ../../../import-events
    volumes:
      - ../../../import-events:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  review:
    build: ../../../review
    volumes:
      - ../../../review:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  labels:
    build: ../../../labels
    volumes:
      - ../../../labels:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  settings:
    build: ../../../settings
    volumes:
      - ../../../settings:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  upload:
    build: ../../../upload
    volumes:
      - ../../../upload:/app
    depends_on:
      - neo4j
    env_file: ./.env
    restart: 'on-failure'

  ui:
    build: ../../../ui
    volumes:
      - ../../../ui:/app
    depends_on:
      - neo4j
      - upload
      - document
      - export
      - import-events
      - labels
      - review
      - settings
    env_file: ./.env
    ports:
      - "${WEB_PORT}:5000"
    restart: 'on-failure'
