version: '3'
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    ports:
      - "5001:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
